### ISSUE TITLE
Reference not found or  The .NET SDK 4.0 or 4.5 tools could not be found

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Data.TypeProviders#21]
### Description

I did a fresh install of VS2017 on a Windows 7 machine. When I tried to run a script file with the `FSharp.Data.TypeProviders.dll` the reference was  not found, although it exists on the machine in the `C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0` folder. When using a local packages install I got an error: `The .NET SDK 4.0 or 4.5 tools could not be found`

### Repro steps

Please provide the steps required to reproduce the problem

1. Use a Windows 7 machine

2. Install VS2017 with F# language support

3. Reference the `FSharp.Data.TypeProviders.dll` in a script file

### Expected behavior

The dll can be referenced and used.

### Actual behavior

See above in the description

### Known workarounds

Use the local installed `FSharp.Data.TypeProviders.dll`.
Download and install the SDK for Windows 8.1 (only select the .net SDK).

### Related information 

* Windows 7
* .NET 4.0/4.5

**Comment by dsyme** [comment]
@halcwb If you like please add a bug to http://github.com/Microsoft/visualfsharp about the VS installed package not being found by existing scripts.  

However my recommendation is to please acquire the latest version from the nuget package, not the installed version that comes with Visual Studio. I don't know why that version is not being found, but we'd like people to migrate to the nuget package anyway

**Comment by piers7** [comment]
As of VS 2017.3 it seems like the out-of-box version of the F# type providers is still missing fixes put in several years ago, specifically the PR 638 (https://github.com/Microsoft/visualfsharp/pull/638) referenced in https://github.com/Microsoft/visualfsharp/issues/637 that is supposed to address this. As I've commented in that thread, I looked at the IL, and it looks all the world to be the pre-fix version.

When I swapped to using current version of the nuget package (FSharp.Data.TypeProviders, 5.0.0.2), it all worked fine for me. So I think the OOB version that's being shipped, even as of VS 2017, is really old.

(Clean Win 10 machine with only ever VS 2017 installed)

**Comment by colinbull** [comment]
Despite using the FSharp.Data.TypeProviders Nuget package, I have started getting this on VSTS, which I think is now on VS 2017.5, yesterday (11/12/2017) the build was working fine but now breaks with the above error, with the Version of VS being the only thing that has changed in the context of my build.

Interestingly running the following as part of the build script  

    open System
    open System.IO
    open System.Collections.Generic
    open System.Reflection

    let sdkPath () =
    
        let tryResult (key: Microsoft.Win32.RegistryKey) = 
            match key with 
            | null -> None
            | _ -> 
                let installFolder = key.GetValue("InstallationFolder") :?> string
                if Directory.Exists installFolder then 
                    Some installFolder 
                else
                    None
        // Annoyingly, the F# 2.0 decoding of 'use key = ...' on a registry key doesn't use an null check on the
        // key before calling Dispose. THis is because the key type doesn't use the IDisposable pattern.
        let useKey keyName f =
                // Look for WinSDK reg keys under the 32bit view of the registry.
                let reg32view = Microsoft.Win32.RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.LocalMachine, Microsoft.Win32.RegistryView.Registry32)
                let key = reg32view.OpenSubKey keyName 
                try f key 
                finally 
                    match key with 
                    | null -> () 
                    | _ -> key.Dispose()
                    reg32view.Dispose()     // if reg32view were really null, we would not be here and the user would have more serious issues not being able to access HKLM

        let SDK_REGPATHS = [ @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.2\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\Windows\v7.1\WinSDK-NetFx40Tools"
                             @"Software\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools" ]
    
        SDK_REGPATHS 
        |> Seq.tryPick (fun p -> useKey p tryResult) 
        |> function 
           | Some p -> p
           | _      -> raise <| System.NotSupportedException("Unable to find windows SDK")

    let sdkUtil name = Path.Combine(sdkPath(), name)

    let svcUtilExe () = sdkUtil "svcutil.exe"

actually resolves `svcutil` without an exception. It is only when it is run in the context of a TypeProvider does this fail. Happy to do further investigation, but out of ideas where to look?

**Comment by pavel-khritonenko** [comment]
Fresh windows 10 installation + Default Visual studio 17 (nothing else) - I get this error.

![image](https://user-images.githubusercontent.com/2510026/34209578-c157b802-e5a3-11e7-96d7-458d1865bcb8.png)

![image](https://user-images.githubusercontent.com/2510026/34209588-ce9fab46-e5a3-11e7-8f40-0ff3361a9adf.png)

**Comment by colinbull** [comment]
I think at the least you need one of the Windows SDK's installed. I'm not sure these are installed by default in the Visual Studio 2017.

**Comment by odytrice** [comment]
Was able to work around this by installing VS 2015. Don't know exactly why. But It worked

**Comment by colinbull** [comment]
@odytrice  You don't necessarily need VS2015 installed, you just need one of the Windows SDK's installed,  you need to be able to resolve one of the following registry keys. 

     @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.2\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\Windows\v7.1\WinSDK-NetFx40Tools"
     @"Software\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools"

The only exception to this is when the F# compiler process is ran from a parent process that doesn't have permission to read the registry; on a Visual Studio Team Services for example. Then the call to resolve the registry fails because the parent process doesn't have access. Of course this depends on how the agent was setup, in the first place. 

@dsyme, any chance we can get PR #23 merged? as this will solve this issue. As you can then include `svcutil.exe` as a dependency directly in your repository.

**Comment by lierdakil** [comment]
FWIW I apparently have none of the mentioned registry paths on Windows 10 and VS2017, but instead this: `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools` 
Note the `WOW6432Node` part.

**Comment by lierdakil** [comment]
Hmm. None of the registry manipulation I could think about helped, but installing VS2015 did for some reason. To be clear, installing VS2015 fixed the issue in VS2017. It did *not* add any of the mentioned registry paths though, so probably the issue's not with that necessarily.

**Comment by lierdakil** [comment]
What's even more confusing, the code https://github.com/fsprojects/FSharp.Data.TypeProviders/blob/aae6a2652fcc7434cb77b5de5479bb28aa0c6f8d/src/FSharp.Data.TypeProviders/Util.fs#L82-L118
works by itself both with or without VS2015 and yields `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\`, which is in registry key `HKLM\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools\InstallationFolder` (so I guess `WOW6432Node` is some kind of registry substitution thing for x86 stuff? not sure, not a Windows guy usually)

Contents of `C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\` don't change at all whether VS2015 installed or not.

This all seems rather bizarre to be honest...

**Comment by colinbull** [comment]
@lierdakil As you say the behaviour of this is indeed bizarre and the same as I have seen. However rather than rely on a specific environment for this TP to work I have created a new release (https://www.nuget.org/packages/FSharp.Data.TypeProviders/5.0.0.3-beta) that allows you to specify the path to the svcutil tool you wish to use. This means you can simply include svcutil in your repository, then provide the path. See PR #23 for impl.

**Comment by ghost** [comment]
@colinbull 

I always get the error after running 
` Error reading schema. .NET SDK 4.0 or 4.5 tools could not be found`

Yep, done that
 `open System
open System.IO
open System.Collections.Generic
open System.Reflection

let sdkPath () =

    let tryResult (key: Microsoft.Win32.RegistryKey) = 
        match key with 
        | null -> None
        | _ -> 
            let installFolder = key.GetValue("InstallationFolder") :?> string
            if Directory.Exists installFolder then 
                Some installFolder 
            else
                None
    // Annoyingly, the F# 2.0 decoding of 'use key = ...' on a registry key doesn't use an null check on the
    // key before calling Dispose. THis is because the key type doesn't use the IDisposable pattern.
    let useKey keyName f =
            // Look for WinSDK reg keys under the 32bit view of the registry.
            let reg32view = Microsoft.Win32.RegistryKey.OpenBaseKey(Microsoft.Win32.RegistryHive.LocalMachine, Microsoft.Win32.RegistryView.Registry32)
            let key = reg32view.OpenSubKey keyName 
            try f key 
            finally 
                match key with 
                | null -> () 
                | _ -> key.Dispose()
                reg32view.Dispose()     // if reg32view were really null, we would not be here and the user would have more serious issues not being able to access HKLM

    let SDK_REGPATHS = [ @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.2\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6.1\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\NETFXSDK\4.6\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\Windows\v8.1A\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\Windows\v7.1\WinSDK-NetFx40Tools"
                         @"Software\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools" ]

    SDK_REGPATHS 
    |> Seq.tryPick (fun p -> useKey p tryResult) 
    |> function 
       | Some p -> p
       | _      -> raise <| System.NotSupportedException("Unable to find windows SDK")
let sdkUtil name = Path.Combine(sdkPath(), name)
let svcUtilExe () = sdkUtil "svcutil.exe"`

And I still get `Error reading schema. .NET SDK 4.0 or 4.5 tools could not be found`

**Comment by colinbull** [comment]
@tungandcun Have you tried the latest nuget package -https://www.nuget.org/packages/FSharp.Data.TypeProviders/5.0.0.3-beta ? 

This allows you to specify the location of `svcutil` you can just copy locally to your repository then provide the path to the type provider with the new prarameter.

**Comment by dsyme** [comment]
@colinbull Could you release 5.0.0.4 as non-beta?  With the reg key updates I just pushed? thanks

**Comment by colinbull** [comment]
Done! Can someone else try this now and let me know if it is working or not then I can close this issue. Everything seem ok from my side.

**Comment by dsyme** [comment]
@colinbull Thanks. When you get the chance could you bump the version again and re-release?  The package author is still showing as "Microsoft". I just did a direct submit to remove this - after another update the package author should show as "F# community contributors"

**Comment by colinbull** [comment]
Done! It shows correctly now.
